/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* top =  1  *)
(* src = "designs/RCA/rca.v:1.1-14.10" *)
module rca(A, B, Cin, Sum, Cout);
  (* src = "designs/RCA/rca.v:2.18-2.19" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "designs/RCA/rca.v:3.18-3.19" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "designs/RCA/rca.v:4.18-4.21" *)
  input Cin;
  wire Cin;
  (* src = "designs/RCA/rca.v:6.18-6.22" *)
  output Cout;
  wire Cout;
  (* force_downto = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] Cout_SB_LUT4_O_I2;
  (* hdlname = "FA0 a" *)
  (* src = "designs/RCA/rca.v:10.4-10.64|designs/RCA/fa.v:2.12-2.13" *)
  wire \FA0.a ;
  (* hdlname = "FA0 b" *)
  (* src = "designs/RCA/rca.v:10.4-10.64|designs/RCA/fa.v:3.12-3.13" *)
  wire \FA0.b ;
  (* hdlname = "FA0 cin" *)
  (* src = "designs/RCA/rca.v:10.4-10.64|designs/RCA/fa.v:4.12-4.15" *)
  wire \FA0.cin ;
  (* hdlname = "FA0 sum" *)
  (* src = "designs/RCA/rca.v:10.4-10.64|designs/RCA/fa.v:5.12-5.15" *)
  wire \FA0.sum ;
  (* hdlname = "FA1 a" *)
  (* src = "designs/RCA/rca.v:11.4-11.64|designs/RCA/fa.v:2.12-2.13" *)
  wire \FA1.a ;
  (* hdlname = "FA1 b" *)
  (* src = "designs/RCA/rca.v:11.4-11.64|designs/RCA/fa.v:3.12-3.13" *)
  wire \FA1.b ;
  (* hdlname = "FA1 sum" *)
  (* src = "designs/RCA/rca.v:11.4-11.64|designs/RCA/fa.v:5.12-5.15" *)
  wire \FA1.sum ;
  (* force_downto = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \FA1.sum_SB_LUT4_O_I3 ;
  (* force_downto = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] \FA1.sum_SB_LUT4_O_I3_SB_LUT4_I3_I2 ;
  (* hdlname = "FA2 a" *)
  (* src = "designs/RCA/rca.v:12.4-12.64|designs/RCA/fa.v:2.12-2.13" *)
  wire \FA2.a ;
  (* hdlname = "FA2 b" *)
  (* src = "designs/RCA/rca.v:12.4-12.64|designs/RCA/fa.v:3.12-3.13" *)
  wire \FA2.b ;
  (* hdlname = "FA2 sum" *)
  (* src = "designs/RCA/rca.v:12.4-12.64|designs/RCA/fa.v:5.12-5.15" *)
  wire \FA2.sum ;
  (* force_downto = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \FA2.sum_SB_LUT4_O_I3 ;
  (* hdlname = "FA3 a" *)
  (* src = "designs/RCA/rca.v:13.4-13.66|designs/RCA/fa.v:2.12-2.13" *)
  wire \FA3.a ;
  (* hdlname = "FA3 b" *)
  (* src = "designs/RCA/rca.v:13.4-13.66|designs/RCA/fa.v:3.12-3.13" *)
  wire \FA3.b ;
  (* hdlname = "FA3 cout" *)
  (* src = "designs/RCA/rca.v:13.4-13.66|designs/RCA/fa.v:6.12-6.16" *)
  wire \FA3.cout ;
  (* hdlname = "FA3 sum" *)
  (* src = "designs/RCA/rca.v:13.4-13.66|designs/RCA/fa.v:5.12-5.15" *)
  wire \FA3.sum ;
  (* src = "designs/RCA/rca.v:5.18-5.21" *)
  output [3:0] Sum;
  wire [3:0] Sum;
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfcc0)
  ) Cin_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(Cin),
    .I2(B[0]),
    .I3(A[0]),
    .O(\FA1.sum_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h888e)
  ) Cout_SB_LUT4_O (
    .I0(B[3]),
    .I1(A[3]),
    .I2(Cout_SB_LUT4_O_I2[2]),
    .I3(Cout_SB_LUT4_O_I2[3]),
    .O(Cout)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) Cout_SB_LUT4_O_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(B[2]),
    .I3(A[2]),
    .O(Cout_SB_LUT4_O_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc33c)
  ) \FA0.sum_SB_LUT4_O  (
    .I0(1'h0),
    .I1(Cin),
    .I2(B[0]),
    .I3(A[0]),
    .O(\FA0.sum )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc33c)
  ) \FA1.sum_SB_LUT4_O  (
    .I0(1'h0),
    .I1(B[1]),
    .I2(A[1]),
    .I3(\FA1.sum_SB_LUT4_O_I3 [2]),
    .O(\FA1.sum )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0107)
  ) \FA1.sum_SB_LUT4_O_I3_SB_LUT4_I3  (
    .I0(B[1]),
    .I1(A[1]),
    .I2(\FA1.sum_SB_LUT4_O_I3_SB_LUT4_I3_I2 [2]),
    .I3(\FA1.sum_SB_LUT4_O_I3 [2]),
    .O(Cout_SB_LUT4_O_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) \FA1.sum_SB_LUT4_O_I3_SB_LUT4_I3_I2_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(B[2]),
    .I3(A[2]),
    .O(\FA1.sum_SB_LUT4_O_I3_SB_LUT4_I3_I2 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc33c)
  ) \FA2.sum_SB_LUT4_O  (
    .I0(1'h0),
    .I1(B[2]),
    .I2(A[2]),
    .I3(\FA2.sum_SB_LUT4_O_I3 [2]),
    .O(\FA2.sum )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfcc0)
  ) \FA2.sum_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(1'h0),
    .I1(B[1]),
    .I2(A[1]),
    .I3(\FA1.sum_SB_LUT4_O_I3 [2]),
    .O(\FA2.sum_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/build/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6669)
  ) \FA3.sum_SB_LUT4_O  (
    .I0(B[3]),
    .I1(A[3]),
    .I2(Cout_SB_LUT4_O_I2[2]),
    .I3(Cout_SB_LUT4_O_I2[3]),
    .O(\FA3.sum )
  );
  assign Cout_SB_LUT4_O_I2[1:0] = { A[3], B[3] };
  assign \FA2.sum_SB_LUT4_O_I3 [1:0] = { A[2], B[2] };
  assign \FA1.sum_SB_LUT4_O_I3 [1:0] = { A[1], B[1] };
  assign { \FA1.sum_SB_LUT4_O_I3_SB_LUT4_I3_I2 [3], \FA1.sum_SB_LUT4_O_I3_SB_LUT4_I3_I2 [1:0] } = { \FA1.sum_SB_LUT4_O_I3 [2], A[1], B[1] };
  assign \FA0.a  = A[0];
  assign \FA0.b  = B[0];
  assign \FA0.cin  = Cin;
  assign \FA1.a  = A[1];
  assign \FA1.b  = B[1];
  assign \FA2.a  = A[2];
  assign \FA2.b  = B[2];
  assign \FA3.a  = A[3];
  assign \FA3.b  = B[3];
  assign \FA3.cout  = Cout;
  assign Sum = { \FA3.sum , \FA2.sum , \FA1.sum , \FA0.sum  };
endmodule
