/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* src = "designs/RCA/fa.v:1.1-10.10" *)
module fa(a, b, cin, sum, cout);
  (* src = "designs/RCA/fa.v:2.12-2.13" *)
  input a;
  wire a;
  (* src = "designs/RCA/fa.v:3.12-3.13" *)
  input b;
  wire b;
  (* src = "designs/RCA/fa.v:4.12-4.15" *)
  input cin;
  wire cin;
  (* src = "designs/RCA/fa.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "designs/RCA/fa.v:5.12-5.15" *)
  output sum;
  wire sum;
  sky130_fd_sc_hd__xor3_1 _0_ (
    .A(b),
    .B(a),
    .C(cin),
    .X(sum)
  );
  sky130_fd_sc_hd__maj3_1 _1_ (
    .A(b),
    .B(a),
    .C(cin),
    .X(cout)
  );
endmodule

(* top =  1  *)
(* src = "designs/RCA/rca.v:1.1-14.10" *)
module rca(A, B, Cin, Sum, Cout);
  (* src = "designs/RCA/rca.v:2.18-2.19" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "designs/RCA/rca.v:3.18-3.19" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "designs/RCA/rca.v:4.18-4.21" *)
  input Cin;
  wire Cin;
  (* src = "designs/RCA/rca.v:6.18-6.22" *)
  output Cout;
  wire Cout;
  (* src = "designs/RCA/rca.v:5.18-5.21" *)
  output [3:0] Sum;
  wire [3:0] Sum;
  (* src = "designs/RCA/rca.v:8.6-8.8" *)
  wire c1;
  (* src = "designs/RCA/rca.v:8.10-8.12" *)
  wire c2;
  (* src = "designs/RCA/rca.v:8.14-8.16" *)
  wire c3;
  (* module_not_derived = 32'd1 *)
  (* src = "designs/RCA/rca.v:10.4-10.64" *)
  fa FA0 (
    .a(A[0]),
    .b(B[0]),
    .cin(Cin),
    .cout(c1),
    .sum(Sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "designs/RCA/rca.v:11.4-11.64" *)
  fa FA1 (
    .a(A[1]),
    .b(B[1]),
    .cin(c1),
    .cout(c2),
    .sum(Sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "designs/RCA/rca.v:12.4-12.64" *)
  fa FA2 (
    .a(A[2]),
    .b(B[2]),
    .cin(c2),
    .cout(c3),
    .sum(Sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "designs/RCA/rca.v:13.4-13.66" *)
  fa FA3 (
    .a(A[3]),
    .b(B[3]),
    .cin(c3),
    .cout(Cout),
    .sum(Sum[3])
  );
endmodule
